#define WMG_DEBUG_WINDOW                                        (WM_USER +    1)
#define WMG_SET_POINTER                                         (WM_USER +    2)
#define WMG_FUNCTION_SET_EXPRESSION                             (WM_USER +    3)

#define WMEVAL_ERROR                                            (WM_USER + 4000)
#define WMEVAL_CREATE_PARAMATER                                 (WM_USER + 4003)

#define WMG_FUNCTION_RESULT                                     (WM_USER + 6000)
#define WMG_FUNCTION_START                                      (WM_USER + 6001)
#define WMG_FUNCTION_ENDED                                      (WM_USER + 6002)
#define WMG_FUNCTION_SPEC_ENDED                                 (WM_USER + 6003)

#define WMG_DATAOBJECT_RESULT                                   (WM_USER + 6500)
#define WMG_DATAOBJECT_START                                    (WM_USER + 6501)
#define WMG_DATAOBJECT_ENDED                                    (WM_USER + 6502)

#define WMG_TAKE_DATASET                                        (WM_USER + 7000)

#define WMG_AXIS_SELECT_PROPERTIES                              (WM_USER + 8000)

#define WMG_SETUP                                               (WM_USER + 9000)
#define WMG_SET_VIEW                                            (WM_USER + 9001)
#define WMG_STATUS                                              (WM_USER + 9002)
#define WMG_SET_POSITION                                        (WM_USER + 9003)

#define WMG_DEBUG                                               (WM_USER + 10000) 
